site_name: Documentación CopIA
site_description: Documentación oficial del proyecto CopIA
site_author: Equipo CopIA

theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - "Frank Choquehuanca (CE03: Infraestructura)":
    - "CE0311 - Entregable 1: Diseño de Red": FrankChoquehuanca/entregable1.md
    - "CE0321 - Entregable 2: Planificación de Seguridad": FrankChoquehuanca/entregable2.md
    - "CE0331 - Entregable 3: Diseño de Centro de Datos": FrankChoquehuanca/entregable3.md
    - "CE0312-CE0313 - Entregable 1: Implementación y Testing de Red": FrankChoquehuanca/entregable1-imp.md
    - "CE0322-CE0324 - Entregable 2: Implementación, Monitoreo y Ética de Seguridad": FrankChoquehuanca/entregable2-imp.md
    - "CE0332-CE0333 - Entregable 3: Implementación y Control de Centro de Datos": FrankChoquehuanca/entregable3-imp.md
  - "Christian Salas (CE01: Gestión)":
    - "CE0111-CE0115 - Entregable 1: Diagnóstico Organizacional y Alineamiento Estratégico": ChristianSalas/entregable1.md
    - "CE0113 - Entregable 2: Business Case del Proyecto": ChristianSalas/entregable2.md
    - "CE0121-CE0125 - Entregable 3: Plan de Gestión del Proyecto": ChristianSalas/entregable3.md
    - "CE0131-CE0135 - Entregable 4: Modelado de Procesos AS-IS / TO-BE": ChristianSalas/entregable4.md
    - "CE0141-CE0145 - Entregable 5: Propuesta de Solución TIC Integrada": ChristianSalas/entregable5.md
  - "Cristhian Llanque (CE02: Software)":
    - "CE021 - Entregable 1: Requerimientos y Diseño del Sistema": CristhianLlanque/entregable1.md
    - "CE022 - Entregable 2: Plataforma de Datos del Sistema": CristhianLlanque/entregable2.md
    - "CE023 - Entregable 3: Sistema de Software Funcional Integrado": CristhianLlanque/entregable3.md
    - "CE024 - Entregable 4: Calidad, Operación y Evolución del Sistema": CristhianLlanque/entregable4.md
    - "CE0217 - Entregable 5: Presentación, Video pitch y Sustentación Final": CristhianLlanque/entregable5.md
